### ISSUE TITLE
Hide top bar

### ISSUE THREAD

**Issue by Batwam** [rafgui12/Office365WebDesktop#11]
Hello,

Great work on this tool integrating Office365! I was wondering if it would be possible to have an option to hide the File/Edit/View bar at the top to make it look even better integrated. 
![image](https://user-images.githubusercontent.com/56710655/211260155-d22326f9-27b3-4fea-9dab-3f3a04fb66ff.png)

Most of these should be needed on a regular basis so it would be great if they could be integrated as a hamburger menu like in gnome-terminal:
![image](https://user-images.githubusercontent.com/56710655/211259593-25434e91-54ab-4eda-81ae-7102c04f7eca.png)
or even something like this like in chrome (whichever is easiest): 
![image](https://user-images.githubusercontent.com/56710655/211259642-1646dd86-c8c0-4883-a8a8-c3a9cb6d0e59.png)
Update - Third option: I see from this post that there seem to be options in electron to do this and **show the bar by pressing Alt** which seems like a great solution https://stackoverflow.com/questions/39091964/remove-menubar-from-electron-app

This way it would go from this:
![image](https://user-images.githubusercontent.com/56710655/211259807-a6985420-ec97-49f9-8334-648d86edc255.png)

to this mock-up which looks a bit more compact/modern: 
![image](https://user-images.githubusercontent.com/56710655/211260055-82a06ac9-dc5c-4c09-a821-4c0d5fbd1dae.png)

**Comment by Batwam** [comment]
Any thoughts on this?

**Comment by rafgui12** [comment]
Hi @Batwam Thank you very much for your contribution. If the topBar is already disabled, I'm working on accumulated updates, I'll send you a screenshot, I'll be launching the new version soon

![image](https://user-images.githubusercontent.com/8745105/214495369-b5854084-38ee-486b-a5a6-a6313224dc92.png)

Once again, thank you very much for your contribution.

**Comment by Batwam** [comment]
I just had a look as I didn't notice you had updated it. It looks great, exactly what I was looking for!

**Comment by Batwam** [comment]
Hello and thanks for following up

I tried v.07.1. The main page showing the various apps on the left doesn't have the bar (not sure it ever had it) but when I open a document, it is still showing the top bar. Is this something which should be disabled through options?
