### ISSUE TITLE
Can't open more than one same file type at the same time

### ISSUE THREAD

**Issue by marcoccio** [rafgui12/Office365WebDesktop#2]
I want to open two excel spreadsheets but only one window can be open at any moment, so I can't work with both at the same time. The expected behavior would be to open a new window for every distinct archive, isn't it? I got around this by working from Firefox but still.. I would be nice if it worked.

**Comment by rafgui12** [comment]
Thanks for your comment. I think that these latest versions have been solved. Please update to version 0.7.0. If you have the problem, please let me know. I am waiting for your comments.
